services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: help_desk_api
    ports:
      - "8000:8000"
    volumes:
      - ./help_desk_api:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # Espera o Postgres estar pronto de fato
    restart: on-failure

  db:
    image: postgres:17
    container_name: help_desk_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: help_desk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d help_desk"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: